CREATE TABLE IF NOT EXISTS usuarios (
 id SERIAL PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 email VARCHAR(150) UNIQUE NOT NULL,
 senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS exercicios (
 id SERIAL PRIMARY KEY,
 nome VARCHAR(100) NOT NULL,
 categoria VARCHAR(50) NOT NULL,
 usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE
);
